/*COMANDO UTILIZADO PARA CRIAÇÃO DO BANCO DE DADOS "FACULDADE"*/
CREATE DATABASE FACULDADE
GO

/*COMANDO UTILIZADO PARA UTILIZAÇÃO DO BANCO DE DADOS "FACULDADE" (CRIADO ACIMA)*/
USE FACULDADE
GO

/* CRIÇÃO DA TABELA CIDADE */
CREATE TABLE CIDADES
(
	-- O ID DEVE COMÇAR COM 1 E INCREMENTAR DE 1 EM 1
	CI_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CI_NOME VARCHAR(50) NOT NULL,
	CI_UF CHAR(2) NOT NULL,
)

/* CRIÇÃO DA TABELA PROFESSOR */
CREATE TABLE PROFESSORES
(
	-- O ID DEVE COMÇAR COM 1 E INCREMENTAR DE 1 EM 1
	PR_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	PR_MATRICULA INT NOT NULL,
	PR_NOME VARCHAR(45) NOT NULL,
	PR_RG VARCHAR(15) NOT NULL,
	PR_CPF VARCHAR(11) NOT NULL,
	PR_END_LOGRADOURO VARCHAR(100) NOT NULL,
	PR_END_BAIRRO VARCHAR(45) NOT NULL,
	PR_END_NUMERO VARCHAR(15) NOT NULL,
	PR_END_CEP VARCHAR(8) NOT NULL, 
	-- APENAS AS LETRAS F e M SÃO ACEITAS
	PR_SEXO VARCHAR(1) CONSTRAINT CK_PR_SEXO CHECK ( PR_SEXO IN ('F', 'M')),
	-- RELACIONAMENTO 1:N COM CURSO
	PR_CIDADE_ID INT CONSTRAINT FK_PR_CIDADE_ID FOREIGN KEY (PR_CIDADE_ID)
	REFERENCES CIDADES(CI_ID),
	-- APENAS OS NUMEROS 0 e 1 SÃO ACEITOS
	PR_STATUS TINYINT CONSTRAINT CK_PR_STATUS CHECK (PR_STATUS IN (0, 1))
)

/* CRIÇÃO DA TABELA MATERIA */
CREATE TABLE MATERIAS
(
	-- O ID DEVE COMÇAR COM 1 E INCREMENTAR DE 1 EM 1
	MA_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	MA_NOME VARCHAR(45) NOT NULL,
	MA_DESCRICAO VARCHAR(255) NOT NULL,
	MA_CARGA_HORARIA TINYINT NOT NULL
)

/* CRIÇÃO DA TABELA CURSO */
CREATE TABLE CURSOS
(
	-- O ID DEVE COMÇAR COM 1 E INCREMENTAR DE 1 EM 1
	CU_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	CU_NOME VARCHAR(45) NOT NULL,
	CU_TURNO VARCHAR(45) NOT NULL,
	CU_DESCRICAO VARCHAR(255) NOT NULL,
	CU_SEMESTRES TINYINT NOT NULL
)

/* CRIÇÃO DA TABELA N:M ENTRE MATERIA E CURSO */
CREATE TABLE MATERIAS_CURSOS
(
	-- RELACIONAMENTO 1:N COM MATERIA
	MC_MATERIA_ID INT CONSTRAINT FK_MATERIA_ID FOREIGN KEY (MC_MATERIA_ID)
	REFERENCES MATERIAS(MA_ID),
	-- RELACIONAMENTO 1:N COM CURSO
	MC_CURSO_ID INT CONSTRAINT FK_CURSO_ID FOREIGN KEY (MC_CURSO_ID)
	REFERENCES CURSOS(CU_ID),
	-- DEFINIDO A CHAVE COMPOSTA
	CONSTRAINT PK_MT_CU PRIMARY KEY (MC_MATERIA_ID,MC_CURSO_ID)
)

/* CRIÇÃO DA TABELA N:M ENTRE MATERIA E PROFESSOR */
CREATE TABLE MATERIAS_PROFESSORES
(
	-- RELACIONAMENTO 1:N COM MATERIA
	MP_MATERIA_ID INT CONSTRAINT FK_MATERIA_ID1 FOREIGN KEY (MP_MATERIA_ID)
	REFERENCES MATERIAS(MA_ID),
	-- RELACIONAMENTO 1:N COM PROFESSOR
	MP_PROFESSOR_ID INT CONSTRAINT FK_PROFESSOR_ID FOREIGN KEY (MP_PROFESSOR_ID)
	REFERENCES PROFESSORES(PR_ID),
	-- DEFINIDO A CHAVE COMPOSTA
	CONSTRAINT PK_MT_PR PRIMARY KEY (MP_MATERIA_ID,MP_PROFESSOR_ID)
)

/* CRIÇÃO DA TABELA ALUNO */
CREATE TABLE ALUNOS
(
	-- O ID DEVE COMÇAR COM 1 E INCREMENTAR DE 1 EM 1
	AL_ID INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	AL_RG VARCHAR(15) NOT NULL,
	AL_CPF VARCHAR(11) NOT NULL,
	AL_MATRICULA INT NOT NULL,
	AL_NOME VARCHAR(45) NOT NULL,
	AL_END_LOGRADOURO VARCHAR(100) NOT NULL,
	AL_END_BAIRRO VARCHAR(45) NOT NULL,
	AL_END_NUMERO VARCHAR(15) NOT NULL,
	AL_END_CEP VARCHAR(8) NOT NULL, 
	-- APENAS AS LETRAS F e M SÃO ACEITAS
	AL_SEXO VARCHAR(1) CONSTRAINT CK_AL_SEXO CHECK (AL_SEXO IN ('F','M')),
	-- APENAS OS NUMEROS 0 e 1 SÃO ACEITOS
	AL_STATUS TINYINT CONSTRAINT CK_AL_STATUS CHECK (AL_STATUS IN (0, 1)),
	-- RELACIONAMENTO 1:N COM CURSO
	AL_CURSO_ID INT CONSTRAINT FK_AL_CURSO_ID FOREIGN KEY (AL_CURSO_ID)
	REFERENCES CURSOS(CU_ID),
	-- RELACIONAMENTO 1:N COM CIDADE
	AL_CIDADE_ID INT CONSTRAINT FK_AL_CIDADE_ID FOREIGN KEY (AL_CIDADE_ID)
	REFERENCES CIDADES(CI_ID),
)

INSERT INTO CIDADES (CI_NOME, CI_UF) VALUES 
	('TEIXERIA DE FREITAS', 'BA'),
	('ITAMARAJÚ', 'BA'),
	('CARAVELAS', 'BA'),
	('SALVADOR', 'BA')

INSERT INTO CURSOS (CU_NOME, CU_DESCRICAO, CU_SEMESTRES, CU_TURNO) VALUES
	('CIENCIA DA COMPUTAÇÃO', 'FORMA CIENTISTAS DA COMPUTAÇÃO', 8, 'MATUTINO'),
	('MEDICINA', 'FORMA PROFISSIONAIS CAPAZES DE SALVAR VIDAS', 10, 'VESPERTINO'),
	('DIREITO', 'FORMA PROFISISONAIS PARA DEVEDER A LEI ACIMA DE TUDO', 15, 'NOTURNO'),
	('ENGENHARIA DE AUTOMAÇÃO', 'FORMA PROFISSIONAIS CAPAZES DE CONSTRUIR E PROGRAMAR MAQUINAS', 5, 'INTEGRAL')

INSERT INTO MATERIAS (MA_NOME, MA_CARGA_HORARIA, MA_DESCRICAO) VALUES
	('PROGRAMAÇÃO DE BANCO DE DAODS', 100, 'PROGRAMAÇÃO'),
	('CÁLCULO NUMÉRICO', 50, 'MATEMATICA APLICADA'),
	('DIREITO DO CONSUMIDOR', 80, 'DEFENDE O CONSUMIDOR'),
	('ANATOMIA', 120, 'PARTES DO CORPO HUMANO'),
	('CIRCUITOS DIGITAIS', 35, 'CIRCUITOS INTEGRAIS E DIGITAIS')

INSERT INTO PROFESSORES (PR_CIDADE_ID, PR_CPF, PR_END_BAIRRO, PR_END_CEP, PR_END_LOGRADOURO, PR_END_NUMERO, PR_MATRICULA, PR_NOME, PR_RG, PR_SEXO, PR_STATUS) VALUES
	(1, '01234567891', 'CASTELINHO', '45995000', 'RUA CARNE NA UBA', '24-v', 979, 'JOAO MENDOÇA II', '168885789', 'M', 1),
	(2, '89257567891', 'COLINA VERDE', '45995778', 'RUA EVANGÉLICA', '7789', 981, 'MARIA CRISTINA', '168885790', 'F', 1)

INSERT INTO ALUNOS (AL_CIDADE_ID, AL_CPF, AL_CURSO_ID, AL_END_BAIRRO, AL_END_CEP, AL_END_LOGRADOURO, AL_END_NUMERO, AL_MATRICULA, AL_NOME, AL_RG, AL_SEXO, AL_STATUS) VALUES
	(3, '06615683500', 1, 'SANTA RITA', '45992088', 'RUA VARGINIA SILVA', '8898', '000054', 'JOAO PAULO SANTOS', '7789795545', 'M', 1),
	(4, '06615683577', 3, 'TRANCREDO NEVES', '45992777', 'RUA BAHIA', '7789', '000321', 'DEBORA SILVA', '7789795777', 'F', 1)

INSERT INTO MATERIAS_CURSOS (MC_MATERIA_ID, MC_CURSO_ID) VALUES 
	(1,1), (1,2), (1,3), (1,4), 
	(2,1), (2,2), (2,3), (2,4), 
	(3,1), (3,2), (3,3), (3,4), 
	(4,1), (4,2), (4,3), (4,4), 
	(5,1), (5,2), (5,3), (5,4)

INSERT INTO MATERIAS_PROFESSORES(MP_PROFESSOR_ID, MP_MATERIA_ID) VALUES 
	(1, 1), (1, 2), (1, 5),
	(2, 4)
